### ISSUE TITLE
How are exceptions thrown in getBatched handled?

### ISSUE THREAD

**Issue by njlr** [cmeeren/BatchIt#4]
For example, will the exception get routed back to each caller?

**Comment by cmeeren** [comment]
Yes. If a batch call with 1000 items throws an exception, then all 1000 callers will get the exception. If you log it there, you'll log a lot of exceptions.

I am not entirely happy with this (I occasionally get a lot of exceptions logged in one of my systems that uses batching heavily with large batch sizes), but as far as I know, there is simply no other way: The whole point of BatchIt is to be able to call batched async functions as if they were non-batched. Callers know nothing about each other. As with calling any normal non-batched function, each caller must either get a valid result, or an exception.

**Comment by cmeeren** [comment]
Should you want to avoid handling a potentially large number of exceptions, you must yourself write logic higher up that for example short-circuits on the first exception and only propagates that.

**Comment by njlr** [comment]
Thanks the response. 

I think this approach is very sensible - otherwise the caller may never find out that their request failed.

**Comment by cmeeren** [comment]
Yes, though it's not just about being sensible - it's about having to actually return something at all. Say you have a batched call to get users by ID. If the batched call throws an exception, and the caller should _not_ get an exception, then it must by definition get a user. But there is no user to return. Throwing the exception to the caller is almost by definition the only possible thing to do. Returning `None`, empty arrays, or, `null` would be incorrect in all cases.
