### ISSUE TITLE
Question: caching?

### ISSUE THREAD

**Issue by njlr** [cmeeren/BatchIt#5]
I can't see anything around caching in the docs, however this is a common use-case for tasks that BatchIt is also useful for.

The idea would be that cached requests could resolve immediately and only un-cached requests would hit the batching mechanism. 

I don't think that any sophisticated cache expiry logic is required, since (at least in my use-case) Batch objects only live as long as a user request anyway. 

Assuming the request object is the cache key, this would require that requests implement `comparison`. I think having the requests be simple data types is a good practice anyway.

What are your thoughts on this?

Would a PR in this area be accepted?

**Comment by cmeeren** [comment]
Caching is orthogonal to what BatchIt is trying to accomplish (and is a complex domain in its own right). Simply wrap the batched call in something that performs caching. I personally use [Polly](https://github.com/App-vNext/Polly) for all my caching needs.

Closing, but don't hesitate to ask follow-up questions if needed.

**Comment by njlr** [comment]
The reason I see them as related is due to the various other n-select solutions ([Haxl](https://hackage.haskell.org/package/haxl), [Data Loader](https://github.com/graphql/dataloader)) incorporate caching. 

Regarding Polly, if the batched call is wrapped with a Polly cache, does that mean that the cache hits are unlikely?

To illustrate...

1. Query made for batch `[ A; B ]`

      Cache now contains the key `[ A; B ]`

2. Query made for batch `[ B; C ]`

      Cache _miss_ (since `[ A; B ] <> [ B; C ]`)

      Cache now contains the keys `[ A; B ]` and `[ B; C ]`

However, we could have used the cached response for `B`, if the cache keys were more granular. 

Curious if you have landed on any solutions to this?

**Comment by cmeeren** [comment]
Sorry, I should have been more specific:

The call that fetches a single element (through BatchIt) should be wrapped in a cache. Not the call with all the batched elements. As you have surmised, that is unlikely to yield any cache hits.

Did that make more sense? If not, I can elaborate.

**Comment by njlr** [comment]
Ah, I understand. 

So it would be (pseudo-code):

```fsharp
let fetchBatch requests = ...

let fetchUncached = Batch.Create(fetchBatch, 50, 100, 100)

let fetch = applyPollyCache fetchUncached
```

And `fetch` is what should be used to service requests.


Thanks!

**Comment by cmeeren** [comment]
Yes, that is correct. 👍
